services:
  - type: web
    name: ssag-command-center-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ssag-db
          property: connectionString
